module.exports = [
    {
    strDrink: 'Margarita',
    strIngredient1: 'Tequila',
    striMeasure1: '1 1/2 oz',
    strIngredient2: 'Triple Sec',
    striMeasure2: '1/2 oz',
    strIngredient3: 'Lime Juice',
    striMeasure3: '1 oz',
    strIngredient4: 'Salt',
    strGlass: 'Cocktail glass',
    strInstructions: "Rub the rim of the glass with the lime slice to make the salt stick to it. Take care to moisten only the outer rim and sprinkle the salt on it. The salt should present to the lips of the imbiber and never mix into the cocktail. Shake the other ingredients with ice, then carefully pour into the glass.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/5noda61589575158.jpg",
    strTags: "IBA,ContemporaryClassic",
    strAlcoholic: true
    },
    {
    strDrink: 'Long vodka',
    strIngredient1: 'Vodka',
    ingredient1meas: '5 cl',
    strIngredient2: 'Lime',
    ingredient2meas: '1/2',
    strIngredient3: 'Angostura bitters',
    ingredient3meas: '4 dashes',
    strIngredient4: 'Tonic Water',
    ingredient4meas: '1 dl Schweppes',
    strIngredient5: 'Ice',
    strIngredient5: '4',
    strGlass: 'Highball glass',
    strInstructions: "Shake a tall glass with ice cubes and Angostura, coating the inside of the glass. Por the vodka onto this, add 1 slice of lime and squeeze juice out of remainder, mix with tonic, stir and voila you have a Long Vodka",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/9179i01503565212.jpg",
    strTags: 'the best',
    alcoholic: true,
    },
    {
    strDrink: 'Whiskey Sour',
    strIngredient: 'Blended whiskey',
    strMeasure1: '2 oz',
    strIngredient2: 'Lemon',
    strMeasure2: 'Juice of 1/2',
    strIngredient3: 'Powdered Sugar',
    strMeasure3: '1/2 tsp',
    strIngredient4: 'Cherry',
    strMeasure4: '1',
    strIngredient5: 'Lemon',
    strMeasure5: '1/2 slice',
    strGlass: 'Old-fashioned glass',
    strInstructions: "Shake with ice. Strain into chilled glass, garnish and serve. If served 'On the rocks', strain ingredients into old-fashioned glass filled with ice.",
    strDrinkThumb: "https://www.thecocktaildb.com/images/media/drink/hbkfsh1589574990.jpg",
    strTags: "IBA,Classic,Alcoholic",
    strAlcohlic: true,
    }
]